name: 'Setup Mako'
description: 'Setup the environment for Mako'
runs:
  using: 'composite'
  steps:
    - run: pipx install poetry
      shell: bash

    - run: |
        cd "${{ github.action_path }}/../"
        poetry install --only main
      shell: bash
