name: 'Mako command'
description: 'Execute a Mako subcommand'
inputs:
  command:
    description: 'Subcommand to execute with Mako'
    required: true
  args:
    description: 'Arguments for the specified subcommand'
    required: true
    default: ''
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'Private key for the GitHub App'
    required: true
  installation_id:
    description: 'GitHub App Installation ID'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        poetry -n -C "${{ github.action_path }}../" run ryujinx-mako ${{ inputs.command }} ${{ inputs.args }}
      shell: bash
      env:
        MAKO_APP_ID: ${{ inputs.app_id }}
        MAKO_PRIVATE_KEY: ${{ inputs.private_key }}
        MAKO_INSTALLATION_ID: ${{ inputs.installation_id }}
